# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kolibriauth', '0011_facilitydataset_show_download_button_in_learn'),
        ('lessons', '0002_auto_20180221_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classchannels', to='kolibriauth.Collection')),
            ],
        ),
    ]
