# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_reportsdataoffline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsdataoffline',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
